services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tailorconnect-backend
    ports:
      - "1000:1000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tailorconnect-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
